### ISSUE TITLE
Width Utilities

### ISSUE THREAD

**Issue by charlespeters** [charlespeters/obsidian#128]
```css
.u-wd100   { width: 100%; }
.u-mxw100 { max-width: 100%; }
```

OR

```css
.u-wd--100    { width: 100%; }
.u-mxw--auto { max-width: auto; }
.u-mxw--fit    { max-width: 100%; }
```

more inclined to the 2nd option because the font-weight utilities
