### ISSUE TITLE
Pale Gray

### ISSUE THREAD

**Issue by charlespeters** [charlespeters/obsidian#131]
```css
:root {
  --palegray: #F7F7F7;
}

.u-palegray { color: #F7F7F7; }
.u-bg-palegray { background: #F7F7F7; }
```
