### ISSUE TITLE
Xtra Small Icon

### ISSUE THREAD

**Issue by charlespeters** [charlespeters/obsidian#137]
Add a extra small icon 

```css
:root {
  --icon-size: 3rem;
  --icon-xs: calc(var(--icon-size) * .375);
  --icon-sm: calc(var(--icon-size) * .625);
  --icon-md: calc(var(--icon-size) * 1.125);
  --icon-lg: calc(var(--icon-size) * 1.5);
}

.o-icon--xs {
  width: var(--icon-xs);
  height: var(--icon-xs);
}
```
