### ISSUE TITLE
PostCSS Plugins & Browser Support

### ISSUE THREAD

**Issue by charlespeters** [charlespeters/obsidian#28]
Needs an uncompiled version (that's concatenated)
Might reconsider cssnext for two or three plugins

- `calc()`, `rem` and `var()` have reasonable browser support
- custom properties should have a fallback along side their declaration

```css
a {
   color: #147AAB;
   color: var(--blue, #147AAB);
}
```

### Features to dive into

- Custom Selectors
- Custom Media Queries
- `@apply`
- `color()` function
